// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_y-J9pCy8rRPKOlS4st3aVLkFugTlRiE',
    appId: '1:94886729611:web:0144c1ccc0edd10b93018e',
    messagingSenderId: '94886729611',
    projectId: 'fir-e-dad74',
    authDomain: 'fir-e-dad74.firebaseapp.com',
    storageBucket: 'fir-e-dad74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp3FmejsX1BO6zD7jHhdMWEF-HQd5-IlQ',
    appId: '1:94886729611:android:1989e29f489091a193018e',
    messagingSenderId: '94886729611',
    projectId: 'fir-e-dad74',
    storageBucket: 'fir-e-dad74.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_y-J9pCy8rRPKOlS4st3aVLkFugTlRiE',
    appId: '1:94886729611:web:60098756b7180af193018e',
    messagingSenderId: '94886729611',
    projectId: 'fir-e-dad74',
    authDomain: 'fir-e-dad74.firebaseapp.com',
    storageBucket: 'fir-e-dad74.firebasestorage.app',
  );
}
